CREATE DATABASE IF NOT EXISTS usermanagement;
CREATE DATABASE IF NOT EXISTS address;
CREATE DATABASE IF NOT EXISTS Contacts;
CREATE DATABASE IF NOT EXISTS Labodb;
CREATE DATABASE IF NOT EXISTS TestAnalyse;
CREATE DATABASE IF NOT EXISTS epreuve;
CREATE DATABASE IF NOT EXISTS analyse;
CREATE DATABASE IF NOT EXISTS folders;