eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

server:
  port: 8222

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Referer"
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowCredentials: true

      routes:
        - id: auth-service
          uri: http://auth-service:8085
          #uri: http://localhost:8085
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: http://user-service:8088
          #uri: http://localhost:8088
          predicates:
            - Path=/users/**

        - id: contact-service
          uri: http://contact-service:8885
          #uri: http://localhost:8885
          predicates:
            - Path=/api/contacts/**

        - id: labo-service
          uri: http://labo-service:8886
          #uri: http://localhost:8886
          predicates:
            - Path=/api/laboratoires/**
          filters:
            #- AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST

        - id: address-service
          uri: http://address-service:8084
          #uri: http://localhost:8084
          predicates:
            - Path=/api/addresses/**
          filters:
            #- AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST  # Ajout d'une nouvelle ligne avec la bonne syntaxe

        - id: MicroTest-service
          uri: http://MicroTest-service:8087
          #uri: http://localhost:8087
          predicates:
            - Path=/testanalyses/**
          filters:
            #- AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST  # Ajout d'une nouvelle ligne avec la bonne syntaxe

        - id: epreuve-service
          uri: http://epreuve-service:8889
          #uri: http://localhost:8889
          predicates:
            - Path=/epreuves/**
          filters:
            #- AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST  # Ajout d'une nouvelle ligne avec la bonne syntaxe

        - id: analyse-service
          uri: http://analyse-service:8887
          #uri: http://localhost:8887
          predicates:
            - Path=/analyses/**
          filters:
            #- AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST

        - id: folder-service
          uri: http://folder-service:8898
          #uri: http://localhost:8898
          predicates:
            - Path=/api/folders/**
          filters:
            #- AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST

          # - id: exam-service

          #uri: http://localhost:8899
            #predicates:
          #  - Path=/api/exams/**
            # filters:
            #- AuthenticationFilter
            # - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            # - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST

management:
  tracing:
    sampling:
      probability: 1.0