spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  management:
    endpoints:
      web:
        exposure:
          include: "*"